name: "GateVision"
version: "2.2.5"
slug: "gatevision"
description: "Reconnaissance de plaques avec authentification Digest"
url: "https://github.com/atila593/GateVision"
arch:
  - amd64
  - armv7
  - aarch64
startup: application
boot: auto
host_network: true
options:
  camera_ip: "192.168.1.28"
  camera_port: 80
  camera_user: "admin"
  camera_password: "Olivier59"
  snapshot_channel: "102"
  snapshot_interval: 2
  authorized_plates:
    - "AB123CD"
  mqtt_broker: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  mqtt_topic: "gate/control"
  mqtt_payload: "ON"
schema:
  camera_ip: str
  camera_port: int
  camera_user: str
  camera_password: password
  snapshot_channel: str
  snapshot_interval: int
  authorized_plates:
    - str
  mqtt_broker: str
  mqtt_port: int
  mqtt_user: str?
  mqtt_password: password?
  mqtt_topic: str
  mqtt_payload: str
