name: "GateVision"
description: "Reconnaissance de plaques universelle pour portail et garage"
version: "1.0.1"
slug: "gatevision"
arch:
  - aarch64
  - amd64
  - armv7
init: false
options:
  camera_url: "rtsp://votre_flux"
  authorized_plates:
    - "AB123CD"
  output_method: "MQTT"
  mqtt_broker: "core-mosquitto"
  mqtt_topic: "gate/control"
  mqtt_payload: "ON"
schema:
  camera_url: str
  authorized_plates:
    - str
  output_method: list(MQTT|WEBHOOK)
  mqtt_broker: str?
  mqtt_topic: str?
  mqtt_payload: str?
  webhook_url: str?
