name: "GateVision OCR"
version: "3.0.0"
slug: "gatevision_ocr"
description: "Reconnaissance de plaques universelle via RTSP avec d√©tection de mouvement."
arch:
  - aarch64
  - amd64
  - armv7
init: false
options:
  rtsp_url: "rtsp://admin:password@192.168.1.28:554/Streaming/Channels/102"
  motion_sensitivity: 5000
  authorized_plates:
    - "GT033KV"
    - "DL907HB"
  mqtt_topic: "homeassistant/switch/portail/set"
  mqtt_payload: "ON"
  mqtt_broker: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
schema:
  rtsp_url: str
  motion_sensitivity: int
  authorized_plates:
    - str
  mqtt_topic: str
  mqtt_payload: str
  mqtt_broker: str
  mqtt_port: int
  mqtt_user: str?
  mqtt_password: str?
