name: "GateVision"
version: "1.0.10"
slug: "gatevision"
description: "Reconnaissance de plaques universelle pour portail et garage via MQTT"
url: "https://github.com/atila593/GateVision"
arch:
  - amd64
  - armv7
  - aarch64
startup: application
boot: auto
host_network: true
privileged: ["SYS_RAWIO"]
options:
  camera_url: "rtsp://admin:password@192.168.1.XX:554/live"
  authorized_plates:
    - "AA123BB"
  output_method: "MQTT"
  mqtt_broker: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  mqtt_topic: "gate/control"
  mqtt_payload: "ON"
schema:
  camera_url: str
  authorized_plates:
    - str
  output_method: str
  mqtt_broker: str
  mqtt_port: int
  mqtt_user: str?
  mqtt_password: password?
  mqtt_topic: str
  mqtt_payload: str
